name: Create release tag

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v6
      env:
        version: ${{ steps.latest.outputs.output }}
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${process.env.version}',
            sha: context.sha
          })
